addons:
  postgresql: 11.5
before_script:
  - cp config/database.yml.travis config/database.yml
language: ruby
rvm:
  - 2.6.3
services:
  - sqlite3  
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec

